import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CORE_EXERCISES = [
  {
    name: "Barbell Bench Press",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/barbell_bench_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/barbell_bench_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/barbell_bench_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/barbell_bench_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/barbell_bench_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Barbell Back Squat",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/barbell_back_squat.json",
    gripAnimationUrl: "http://localhost:3000/animations/barbell_back_squat.json",
    postureAnimationUrl: "http://localhost:3000/animations/barbell_back_squat.json",
    movementAnimationUrl: "http://localhost:3000/animations/barbell_back_squat.json",
    loopAnimationUrl: "http://localhost:3000/animations/barbell_back_squat.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Conventional Deadlift",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/conventional_deadlift.json",
    gripAnimationUrl: "http://localhost:3000/animations/conventional_deadlift.json",
    postureAnimationUrl: "http://localhost:3000/animations/conventional_deadlift.json",
    movementAnimationUrl: "http://localhost:3000/animations/conventional_deadlift.json",
    loopAnimationUrl: "http://localhost:3000/animations/conventional_deadlift.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Pull-up",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/pull_up.json",
    gripAnimationUrl: "http://localhost:3000/animations/pull_up.json",
    postureAnimationUrl: "http://localhost:3000/animations/pull_up.json",
    movementAnimationUrl: "http://localhost:3000/animations/pull_up.json",
    loopAnimationUrl: "http://localhost:3000/animations/pull_up.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Overhead Press",
    bodyPart: "Shoulders",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/overhead_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/overhead_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/overhead_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/overhead_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/overhead_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Barbell Row",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/barbell_row.json",
    gripAnimationUrl: "http://localhost:3000/animations/barbell_row.json",
    postureAnimationUrl: "http://localhost:3000/animations/barbell_row.json",
    movementAnimationUrl: "http://localhost:3000/animations/barbell_row.json",
    loopAnimationUrl: "http://localhost:3000/animations/barbell_row.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Lat Pulldown",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/lat_pulldown.json",
    gripAnimationUrl: "http://localhost:3000/animations/lat_pulldown.json",
    postureAnimationUrl: "http://localhost:3000/animations/lat_pulldown.json",
    movementAnimationUrl: "http://localhost:3000/animations/lat_pulldown.json",
    loopAnimationUrl: "http://localhost:3000/animations/lat_pulldown.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Leg Press",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/leg_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/leg_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/leg_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/leg_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/leg_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Leg Extension",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/leg_extension.json",
    gripAnimationUrl: "http://localhost:3000/animations/leg_extension.json",
    postureAnimationUrl: "http://localhost:3000/animations/leg_extension.json",
    movementAnimationUrl: "http://localhost:3000/animations/leg_extension.json",
    loopAnimationUrl: "http://localhost:3000/animations/leg_extension.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Leg Curl",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/leg_curl.json",
    gripAnimationUrl: "http://localhost:3000/animations/leg_curl.json",
    postureAnimationUrl: "http://localhost:3000/animations/leg_curl.json",
    movementAnimationUrl: "http://localhost:3000/animations/leg_curl.json",
    loopAnimationUrl: "http://localhost:3000/animations/leg_curl.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Calf Raise",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/calf_raise.json",
    gripAnimationUrl: "http://localhost:3000/animations/calf_raise.json",
    postureAnimationUrl: "http://localhost:3000/animations/calf_raise.json",
    movementAnimationUrl: "http://localhost:3000/animations/calf_raise.json",
    loopAnimationUrl: "http://localhost:3000/animations/calf_raise.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Dumbbell Curl",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/dumbbell_curl.json",
    gripAnimationUrl: "http://localhost:3000/animations/dumbbell_curl.json",
    postureAnimationUrl: "http://localhost:3000/animations/dumbbell_curl.json",
    movementAnimationUrl: "http://localhost:3000/animations/dumbbell_curl.json",
    loopAnimationUrl: "http://localhost:3000/animations/dumbbell_curl.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Tricep Extension",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/tricep_extension.json",
    gripAnimationUrl: "http://localhost:3000/animations/tricep_extension.json",
    postureAnimationUrl: "http://localhost:3000/animations/tricep_extension.json",
    movementAnimationUrl: "http://localhost:3000/animations/tricep_extension.json",
    loopAnimationUrl: "http://localhost:3000/animations/tricep_extension.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Lateral Raise",
    bodyPart: "Shoulders",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/lateral_raise.json",
    gripAnimationUrl: "http://localhost:3000/animations/lateral_raise.json",
    postureAnimationUrl: "http://localhost:3000/animations/lateral_raise.json",
    movementAnimationUrl: "http://localhost:3000/animations/lateral_raise.json",
    loopAnimationUrl: "http://localhost:3000/animations/lateral_raise.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Front Raise",
    bodyPart: "Shoulders",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/front_raise.json",
    gripAnimationUrl: "http://localhost:3000/animations/front_raise.json",
    postureAnimationUrl: "http://localhost:3000/animations/front_raise.json",
    movementAnimationUrl: "http://localhost:3000/animations/front_raise.json",
    loopAnimationUrl: "http://localhost:3000/animations/front_raise.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Shrugs",
    bodyPart: "Shoulders",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/shrugs.json",
    gripAnimationUrl: "http://localhost:3000/animations/shrugs.json",
    postureAnimationUrl: "http://localhost:3000/animations/shrugs.json",
    movementAnimationUrl: "http://localhost:3000/animations/shrugs.json",
    loopAnimationUrl: "http://localhost:3000/animations/shrugs.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Incline Bench Press",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/incline_bench_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/incline_bench_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/incline_bench_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/incline_bench_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/incline_bench_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Decline Bench Press",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/decline_bench_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/decline_bench_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/decline_bench_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/decline_bench_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/decline_bench_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Dumbbell Fly",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/dumbbell_fly.json",
    gripAnimationUrl: "http://localhost:3000/animations/dumbbell_fly.json",
    postureAnimationUrl: "http://localhost:3000/animations/dumbbell_fly.json",
    movementAnimationUrl: "http://localhost:3000/animations/dumbbell_fly.json",
    loopAnimationUrl: "http://localhost:3000/animations/dumbbell_fly.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Cable Crossover",
    bodyPart: "Full Body",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/cable_crossover.json",
    gripAnimationUrl: "http://localhost:3000/animations/cable_crossover.json",
    postureAnimationUrl: "http://localhost:3000/animations/cable_crossover.json",
    movementAnimationUrl: "http://localhost:3000/animations/cable_crossover.json",
    loopAnimationUrl: "http://localhost:3000/animations/cable_crossover.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Hack Squat",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/hack_squat.json",
    gripAnimationUrl: "http://localhost:3000/animations/hack_squat.json",
    postureAnimationUrl: "http://localhost:3000/animations/hack_squat.json",
    movementAnimationUrl: "http://localhost:3000/animations/hack_squat.json",
    loopAnimationUrl: "http://localhost:3000/animations/hack_squat.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Bulgarian Split Squat",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/bulgarian_split_squat.json",
    gripAnimationUrl: "http://localhost:3000/animations/bulgarian_split_squat.json",
    postureAnimationUrl: "http://localhost:3000/animations/bulgarian_split_squat.json",
    movementAnimationUrl: "http://localhost:3000/animations/bulgarian_split_squat.json",
    loopAnimationUrl: "http://localhost:3000/animations/bulgarian_split_squat.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Romanian Deadlift",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/romanian_deadlift.json",
    gripAnimationUrl: "http://localhost:3000/animations/romanian_deadlift.json",
    postureAnimationUrl: "http://localhost:3000/animations/romanian_deadlift.json",
    movementAnimationUrl: "http://localhost:3000/animations/romanian_deadlift.json",
    loopAnimationUrl: "http://localhost:3000/animations/romanian_deadlift.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Lunges",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/lunges.json",
    gripAnimationUrl: "http://localhost:3000/animations/lunges.json",
    postureAnimationUrl: "http://localhost:3000/animations/lunges.json",
    movementAnimationUrl: "http://localhost:3000/animations/lunges.json",
    loopAnimationUrl: "http://localhost:3000/animations/lunges.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Glute Bridge",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/glute_bridge.json",
    gripAnimationUrl: "http://localhost:3000/animations/glute_bridge.json",
    postureAnimationUrl: "http://localhost:3000/animations/glute_bridge.json",
    movementAnimationUrl: "http://localhost:3000/animations/glute_bridge.json",
    loopAnimationUrl: "http://localhost:3000/animations/glute_bridge.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Hip Thrust",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/hip_thrust.json",
    gripAnimationUrl: "http://localhost:3000/animations/hip_thrust.json",
    postureAnimationUrl: "http://localhost:3000/animations/hip_thrust.json",
    movementAnimationUrl: "http://localhost:3000/animations/hip_thrust.json",
    loopAnimationUrl: "http://localhost:3000/animations/hip_thrust.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Seated Cable Row",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/seated_cable_row.json",
    gripAnimationUrl: "http://localhost:3000/animations/seated_cable_row.json",
    postureAnimationUrl: "http://localhost:3000/animations/seated_cable_row.json",
    movementAnimationUrl: "http://localhost:3000/animations/seated_cable_row.json",
    loopAnimationUrl: "http://localhost:3000/animations/seated_cable_row.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "T-Bar Row",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/t_bar_row.json",
    gripAnimationUrl: "http://localhost:3000/animations/t_bar_row.json",
    postureAnimationUrl: "http://localhost:3000/animations/t_bar_row.json",
    movementAnimationUrl: "http://localhost:3000/animations/t_bar_row.json",
    loopAnimationUrl: "http://localhost:3000/animations/t_bar_row.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Face Pull",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/face_pull.json",
    gripAnimationUrl: "http://localhost:3000/animations/face_pull.json",
    postureAnimationUrl: "http://localhost:3000/animations/face_pull.json",
    movementAnimationUrl: "http://localhost:3000/animations/face_pull.json",
    loopAnimationUrl: "http://localhost:3000/animations/face_pull.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Arnold Press",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/arnold_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/arnold_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/arnold_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/arnold_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/arnold_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Upright Row",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/upright_row.json",
    gripAnimationUrl: "http://localhost:3000/animations/upright_row.json",
    postureAnimationUrl: "http://localhost:3000/animations/upright_row.json",
    movementAnimationUrl: "http://localhost:3000/animations/upright_row.json",
    loopAnimationUrl: "http://localhost:3000/animations/upright_row.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Preacher Curl",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/preacher_curl.json",
    gripAnimationUrl: "http://localhost:3000/animations/preacher_curl.json",
    postureAnimationUrl: "http://localhost:3000/animations/preacher_curl.json",
    movementAnimationUrl: "http://localhost:3000/animations/preacher_curl.json",
    loopAnimationUrl: "http://localhost:3000/animations/preacher_curl.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Hammer Curl",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/hammer_curl.json",
    gripAnimationUrl: "http://localhost:3000/animations/hammer_curl.json",
    postureAnimationUrl: "http://localhost:3000/animations/hammer_curl.json",
    movementAnimationUrl: "http://localhost:3000/animations/hammer_curl.json",
    loopAnimationUrl: "http://localhost:3000/animations/hammer_curl.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Skull Crusher",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/skull_crusher.json",
    gripAnimationUrl: "http://localhost:3000/animations/skull_crusher.json",
    postureAnimationUrl: "http://localhost:3000/animations/skull_crusher.json",
    movementAnimationUrl: "http://localhost:3000/animations/skull_crusher.json",
    loopAnimationUrl: "http://localhost:3000/animations/skull_crusher.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Tricep Pushdown",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/tricep_pushdown.json",
    gripAnimationUrl: "http://localhost:3000/animations/tricep_pushdown.json",
    postureAnimationUrl: "http://localhost:3000/animations/tricep_pushdown.json",
    movementAnimationUrl: "http://localhost:3000/animations/tricep_pushdown.json",
    loopAnimationUrl: "http://localhost:3000/animations/tricep_pushdown.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Dips",
    bodyPart: "Arms",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/dips.json",
    gripAnimationUrl: "http://localhost:3000/animations/dips.json",
    postureAnimationUrl: "http://localhost:3000/animations/dips.json",
    movementAnimationUrl: "http://localhost:3000/animations/dips.json",
    loopAnimationUrl: "http://localhost:3000/animations/dips.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Close Grip Bench Press",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/close_grip_bench_press.json",
    gripAnimationUrl: "http://localhost:3000/animations/close_grip_bench_press.json",
    postureAnimationUrl: "http://localhost:3000/animations/close_grip_bench_press.json",
    movementAnimationUrl: "http://localhost:3000/animations/close_grip_bench_press.json",
    loopAnimationUrl: "http://localhost:3000/animations/close_grip_bench_press.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Crunches",
    bodyPart: "Core",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/crunches.json",
    gripAnimationUrl: "http://localhost:3000/animations/crunches.json",
    postureAnimationUrl: "http://localhost:3000/animations/crunches.json",
    movementAnimationUrl: "http://localhost:3000/animations/crunches.json",
    loopAnimationUrl: "http://localhost:3000/animations/crunches.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Leg Raises",
    bodyPart: "Legs",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/leg_raises.json",
    gripAnimationUrl: "http://localhost:3000/animations/leg_raises.json",
    postureAnimationUrl: "http://localhost:3000/animations/leg_raises.json",
    movementAnimationUrl: "http://localhost:3000/animations/leg_raises.json",
    loopAnimationUrl: "http://localhost:3000/animations/leg_raises.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Plank",
    bodyPart: "Core",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/plank.json",
    gripAnimationUrl: "http://localhost:3000/animations/plank.json",
    postureAnimationUrl: "http://localhost:3000/animations/plank.json",
    movementAnimationUrl: "http://localhost:3000/animations/plank.json",
    loopAnimationUrl: "http://localhost:3000/animations/plank.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Russian Twist",
    bodyPart: "Core",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/russian_twist.json",
    gripAnimationUrl: "http://localhost:3000/animations/russian_twist.json",
    postureAnimationUrl: "http://localhost:3000/animations/russian_twist.json",
    movementAnimationUrl: "http://localhost:3000/animations/russian_twist.json",
    loopAnimationUrl: "http://localhost:3000/animations/russian_twist.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Ab Wheel Rollout",
    bodyPart: "Core",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/ab_wheel_rollout.json",
    gripAnimationUrl: "http://localhost:3000/animations/ab_wheel_rollout.json",
    postureAnimationUrl: "http://localhost:3000/animations/ab_wheel_rollout.json",
    movementAnimationUrl: "http://localhost:3000/animations/ab_wheel_rollout.json",
    loopAnimationUrl: "http://localhost:3000/animations/ab_wheel_rollout.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Cable Crunch",
    bodyPart: "Core",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/cable_crunch.json",
    gripAnimationUrl: "http://localhost:3000/animations/cable_crunch.json",
    postureAnimationUrl: "http://localhost:3000/animations/cable_crunch.json",
    movementAnimationUrl: "http://localhost:3000/animations/cable_crunch.json",
    loopAnimationUrl: "http://localhost:3000/animations/cable_crunch.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Woodchopper",
    bodyPart: "Core",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/woodchopper.json",
    gripAnimationUrl: "http://localhost:3000/animations/woodchopper.json",
    postureAnimationUrl: "http://localhost:3000/animations/woodchopper.json",
    movementAnimationUrl: "http://localhost:3000/animations/woodchopper.json",
    loopAnimationUrl: "http://localhost:3000/animations/woodchopper.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Box Jump",
    bodyPart: "Full Body",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/box_jump.json",
    gripAnimationUrl: "http://localhost:3000/animations/box_jump.json",
    postureAnimationUrl: "http://localhost:3000/animations/box_jump.json",
    movementAnimationUrl: "http://localhost:3000/animations/box_jump.json",
    loopAnimationUrl: "http://localhost:3000/animations/box_jump.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Kettlebell Swing",
    bodyPart: "Full Body",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/kettlebell_swing.json",
    gripAnimationUrl: "http://localhost:3000/animations/kettlebell_swing.json",
    postureAnimationUrl: "http://localhost:3000/animations/kettlebell_swing.json",
    movementAnimationUrl: "http://localhost:3000/animations/kettlebell_swing.json",
    loopAnimationUrl: "http://localhost:3000/animations/kettlebell_swing.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Farmer's Walk",
    bodyPart: "Full Body",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/farmer_s_walk.json",
    gripAnimationUrl: "http://localhost:3000/animations/farmer_s_walk.json",
    postureAnimationUrl: "http://localhost:3000/animations/farmer_s_walk.json",
    movementAnimationUrl: "http://localhost:3000/animations/farmer_s_walk.json",
    loopAnimationUrl: "http://localhost:3000/animations/farmer_s_walk.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Back Extension",
    bodyPart: "Back",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/back_extension.json",
    gripAnimationUrl: "http://localhost:3000/animations/back_extension.json",
    postureAnimationUrl: "http://localhost:3000/animations/back_extension.json",
    movementAnimationUrl: "http://localhost:3000/animations/back_extension.json",
    loopAnimationUrl: "http://localhost:3000/animations/back_extension.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Machine Fly",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/machine_fly.json",
    gripAnimationUrl: "http://localhost:3000/animations/machine_fly.json",
    postureAnimationUrl: "http://localhost:3000/animations/machine_fly.json",
    movementAnimationUrl: "http://localhost:3000/animations/machine_fly.json",
    loopAnimationUrl: "http://localhost:3000/animations/machine_fly.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
  {
    name: "Reverse Pec Deck",
    bodyPart: "Chest",
    targetMuscles: '["Primary Muscle"]',
    secondaryMuscles: '["Secondary Muscle"]',
    equipment: "Gym Equipment",
    difficulty: "Medium",
    setupAnimationUrl: "http://localhost:3000/animations/reverse_pec_deck.json",
    gripAnimationUrl: "http://localhost:3000/animations/reverse_pec_deck.json",
    postureAnimationUrl: "http://localhost:3000/animations/reverse_pec_deck.json",
    movementAnimationUrl: "http://localhost:3000/animations/reverse_pec_deck.json",
    loopAnimationUrl: "http://localhost:3000/animations/reverse_pec_deck.json",
    instructions: '["Step 1: Setup","Step 2: Execute movement","Step 3: Return to start"]'
  },
];

async function main() {
  console.log('Clearing existing workout data to prevent FK constraint errors...');
  await prisma.workoutSet.deleteMany();
  await prisma.workoutExercise.deleteMany();
  await prisma.workoutSession.deleteMany();
  console.log('Clearing existing exercises...');
  await prisma.exercise.deleteMany();
  console.log(`Seeding ${CORE_EXERCISES.length} core exercises...`);
  for (const ex of CORE_EXERCISES) {
    await prisma.exercise.create({ data: ex });
  }
  console.log('Seeding completed successfully!');
}

main().catch(e => console.error(e)).finally(async () => await prisma.$disconnect());
