import React, { useEffect, useState } from 'react';
import { Card } from '../components/ui/Card';
import { Activity, Download, FileText, CheckCircle2, AlertTriangle, ArrowLeft } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface VerificationReport {
  agent1Raw: string;
  agent2Raw: string;
  agent3Raw: string;
  confidenceScore: number;
}

export default function ExpertReport() {
  const { token, user } = useAuth();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [report, setReport] = useState<VerificationReport | null>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  useEffect(() => {
    if (!token) return;

    const fetchReport = async () => {
      try {
        const planRes = await fetch('http://localhost:3000/api/v1/plans/latest', {
          headers: { Authorization: `Bearer ${token}` }
        });
        const planData = await planRes.json();
        if (planData.plan?.verificationReport) {
          setReport(planData.plan.verificationReport);
        }
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, [token]);

  if (loading) {
    return <div className="min-h-screen bg-black text-white flex items-center justify-center">Loading Report...</div>;
  }

  const parseJsonStr = (str: string | undefined) => {
    if (!str) return null;
    try { return JSON.parse(str); } catch { return null; }
  };

  const handleDownloadPDF = () => {
    if (!report) return;
    setIsGeneratingPdf(true);

    const doc = new jsPDF();
    const agent1 = parseJsonStr(report.agent1Raw);
    const agent2 = parseJsonStr(report.agent2Raw);
    const agent3 = parseJsonStr(report.agent3Raw);

    // Title
    doc.setFontSize(22);
    doc.setTextColor(0, 0, 0);
    doc.text('LuminaFit Clinical Nutrition Report', 14, 20);

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Patient: ${user?.name || 'Unknown'} | Confidence Score: ${report.confidenceScore}%`, 14, 30);
    doc.line(14, 35, 196, 35);

    // AI Insight
    if (agent3?.aiInsight) {
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Clinical Synthesis', 14, 45);
      
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      const splitText = doc.splitTextToSize(`"${agent3.aiInsight}"`, 180);
      doc.text(splitText, 14, 55);
    }

    // QA Review Details
    let yPos = 80;
    if (agent2?.issuesFound?.length > 0 || agent2?.suggestions?.length > 0) {
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('QA Review Findings', 14, yPos);
      yPos += 10;

      if (agent2?.issuesFound?.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(200, 0, 0);
        doc.text('Issues Identified:', 14, yPos);
        yPos += 6;
        agent2.issuesFound.forEach((issue: string) => {
          doc.text(`• ${issue}`, 18, yPos);
          yPos += 6;
        });
        yPos += 4;
      }

      if (agent2?.suggestions?.length > 0) {
        doc.setFontSize(10);
        doc.setTextColor(200, 150, 0);
        doc.text('Suggestions:', 14, yPos);
        yPos += 6;
        agent2.suggestions.forEach((sug: string) => {
          doc.text(`• ${sug}`, 18, yPos);
          yPos += 6;
        });
      }
      yPos += 10;
    }

    // Optimizer Corrections
    if (agent3?.correctionsApplied?.length > 0) {
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Optimizer Corrections Applied', 14, yPos);
      yPos += 10;
      doc.setFontSize(10);
      doc.setTextColor(0, 150, 0);
      agent3.correctionsApplied.forEach((corr: string) => {
        doc.text(`• ${corr}`, 14, yPos);
        yPos += 6;
      });
      yPos += 10;
    }

    // Meals Table
    const meals = agent3?.meals || agent1?.meals || [];
    if (meals.length > 0) {
      autoTable(doc, {
        startY: yPos,
        head: [['Meal', 'Time', 'Calories', 'Macros (P/C/F)']],
        body: meals.map((m: any) => [
          m.name,
          m.time || '-',
          `${m.calories} kcal`,
          `${m.macros?.protein}g / ${m.macros?.carbs}g / ${m.macros?.fats}g`
        ]),
        theme: 'striped',
        headStyles: { fillColor: [40, 40, 40] }
      });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by LuminaFit Agent Ecosystem | Page ${i} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10
      );
    }

    doc.save(`LuminaFit_Report_${user?.name?.replace(/\s+/g, '_')}.pdf`);
    setIsGeneratingPdf(false);
  };

  return (
    <div className="min-h-screen bg-black text-white p-8">
      <div className="max-w-3xl mx-auto">
        <button 
          onClick={() => navigate('/dashboard')}
          className="flex items-center gap-2 text-zinc-500 hover:text-white transition-colors mb-8"
        >
          <ArrowLeft size={16} /> Back to Dashboard
        </button>

        <header className="mb-12 text-center">
          <div className="w-16 h-16 bg-zinc-900 border border-zinc-800 rounded-full flex items-center justify-center mx-auto mb-4">
            <Activity className="text-emerald-500" size={32} />
          </div>
          <h1 className="text-3xl font-semibold tracking-tight">Clinical Dietician Report</h1>
          <p className="text-zinc-500 mt-2 max-w-lg mx-auto">
            Your highly personalized nutrition protocol has been thoroughly reviewed and optimized by our multi-agent QA system.
          </p>
        </header>

        <Card className="bg-zinc-950 border-zinc-800 p-8">
          <div className="flex flex-col items-center justify-center py-8">
            
            <div className="text-center mb-8">
              <div className="flex items-center justify-center gap-3 mb-2">
                <CheckCircle2 className="text-emerald-500" size={24} />
                <h2 className="text-2xl font-medium">Report Ready</h2>
              </div>
              <p className="text-zinc-400">
                The QA system assigned a confidence score of 
                <span className={`font-bold ml-1 ${report?.confidenceScore && report.confidenceScore >= 90 ? 'text-emerald-400' : 'text-yellow-400'}`}>
                  {report?.confidenceScore || 'N/A'}%
                </span>.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md">
              <button 
                onClick={handleDownloadPDF}
                disabled={isGeneratingPdf || !report}
                className="flex-1 flex items-center justify-center gap-2 bg-white text-black py-3 px-6 rounded-lg font-medium hover:bg-zinc-200 transition-colors disabled:opacity-50"
              >
                {isGeneratingPdf ? 'Generating...' : (
                  <>
                    <Download size={18} />
                    Download PDF
                  </>
                )}
              </button>
            </div>

            <div className="mt-8 p-4 bg-zinc-900/50 border border-zinc-800/50 rounded-xl max-w-md text-sm text-zinc-500 flex items-start gap-3">
              <AlertTriangle className="text-yellow-500 flex-shrink-0" size={16} />
              <p>
                To protect our proprietary IP, we no longer expose the raw internal chain-of-thought of our Agent Models. 
                Please download the sanitized PDF for a readable clinical overview.
              </p>
            </div>

          </div>
        </Card>
      </div>
    </div>
  );
}
